development:
  adapter: postgresql
  database: tadaaa_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tadaaa_test
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  database: tadaaa_prod
  pool: 5
  timeout: 5000
